"""add_runtime_to_user_movies

Revision ID: 133a7338c3d2
Revises: b7e1c4a92d10
Create Date: 2026-09-26 22:05:55.239181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133a7338c3d2'
down_revision: Union[str, Sequence[str], None] = 'b7e1c4a92d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_movies', sa.Column('runtime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_movies', 'runtime')
    # ### end Alembic commands ###
